/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

#ifndef PROTOBUF_C_student_2eproto__INCLUDED
#define PROTOBUF_C_student_2eproto__INCLUDED

#include <google/protobuf-c/protobuf-c.h>

PROTOBUF_C_BEGIN_DECLS


typedef struct _CStudent CStudent;


/* --- enums --- */


/* --- messages --- */

struct  _CStudent
{
  ProtobufCMessage base;
  char *name;
  char *birthdate;
  protobuf_c_boolean has_age;
  uint32_t age;
  protobuf_c_boolean has_score;
  uint32_t score;
};
#define CSTUDENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cstudent__descriptor) \
    , NULL, NULL, 0,0, 0,0 }


/* CStudent methods */
void   cstudent__init
                     (CStudent         *message);
size_t cstudent__get_packed_size
                     (const CStudent   *message);
size_t cstudent__pack
                     (const CStudent   *message,
                      uint8_t             *out);
size_t cstudent__pack_to_buffer
                     (const CStudent   *message,
                      ProtobufCBuffer     *buffer);
CStudent *
       cstudent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cstudent__free_unpacked
                     (CStudent *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CStudent_Closure)
                 (const CStudent *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cstudent__descriptor;

PROTOBUF_C_END_DECLS


#endif  /* PROTOBUF_student_2eproto__INCLUDED */
